name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereq
      run: sudo apt-get install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
    - name: autogen
      run: ./autogen.sh  --enable-static -host=arm-linux-androideabi
    - name: make
      run: |
        make
        ls
        ls src/.libs
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: libs.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: src/.libs/

