name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereq
      run: sudo apt-get install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
    - name: Install NDK
      run: |
        wget  https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-android-${GSTREAMER_NAME}-1.14.4.tar.bz2 
        tar jxf gstreamer-1.0-android-${GSTREAMER_NAME}-1.14.4.tar.bz2 
        wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip 
        unzip android-ndk-r20-linux-x86_64.zip 
        export ANDROID_NDK_ROOT=`pwd`/android-ndk-r20 
        export ANDROID_SDK_ROOT=/usr/local/android-sdk 
        export PATH=`pwd`/android-ndk-r20:$PATH
        ./autogen.sh  --enable-static -host=arm-linux-androideabi
    - name: make
      run: |
        make
        ls
        ls src/.libs
    - name: file info
      run: file src/.libs/libgdiplus.so
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: libgdiplus.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: src/.libs/libgdiplus.so

