name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereq
      run: sudo apt-get install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
    - name: autogen
      run: UNAME=Android CROSS_COMPILE=arm-linux-androideabi- CC=arm-linux-androideabi-gcc ./autogen.sh  --enable-static
    - name: configure
      run: ./configure
    - name: make
      run: |
        make
        ls
        ls src/.libs
      

