name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereq
      run: sudo apt-get install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
    - name: arch
      run: sudo dpkg --add-architecture arm64
    - name: arch
      run:     sudo apt-get update | true
    - name: arch
      run:    sudo apt-get build-dep -a arm64 libcairo2-dev
    - name: Install NDK
      run: |
        wget --quiet https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip 
        unzip android-ndk-r20-linux-x86_64.zip 
        export ANDROID_NDK_ROOT=`pwd`/android-ndk-r20 
        export ANDROID_SDK_ROOT=/usr/local/android-sdk 
        export PATH=`pwd`/android-ndk-r20:`pwd`/android-ndk-r20/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:`pwd`/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export SYSROOT=$ANDROID_NDK_ROOT/platforms/android-24/arch-arm64
        # Tell configure what tools to use.
        export AR=aarch64-linux-android-ar
        export AS=aarch64-linux-android-as
        export CC=aarch64-linux-android24-clang
        export CXX=aarch64-linux-android24-clang++
        export LD=aarch64-linux-android-ld
        export STRIP=aarch64-linux-android-strip

        # Tell configure what flags Android requires.
        export CFLAGS="-fPIE -fPIC"
        export LDFLAGS="-pie"
        ./autogen.sh  --enable-static --without-x11 --without-libexif -host=aarch64-linux-android
        make
        ls
        ls src/.libs
    - name: file info
      run: file src/.libs/libgdiplus.so
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: libgdiplus.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: src/.libs/libgdiplus.so

