name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereq
      run: sudo apt-get install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-static
    - name: make
      run: |
        make
        ls
        ls lib
      

